### ISSUE TITLE
Fix migrated amount shown after migration

### ISSUE THREAD

**Issue by maptuhec** [LimeChain/aepp-token-migration#8]
When the users migrate their tokens, a modal is shown with the migrated amount which is wrong. It is almost always 9.2***.
![Ã¦ternity Token Migration 2019-11-12 09-07-49.png](https://images.zenhubusercontent.com/5c99f315e4ed6a0001a64d8a/1251e041-10b1-4f71-9210-d848b95e1df6)

**Comment by maptuhec** [comment]
Here is info about one of the accounts with stnrage amount
```
hash:th_2rXYHVfRErZtA9V2kk6rxufoTwbHruezLkqguiMvP4XGvUaSFj
My eth adress:0x005F99afA575cee39D27A06A5632338F53262
I was tring to migrate first time to : ak_2Bct3LTjNBXMAipe2vgr5inoEns6j5xvXJhdf9AuunRKwZUC5P and after that I maked a new wallet ak_FHSxp4Gd25TWMeUEXy7kFYVCfncNUU46hdwRGPh4BRoZMy4ac
```

**Comment by maptuhec** [comment]
Another accoutns is:

ETH: 0xafda522e2576de46f4f65bcffb6a461d4598f387
AE: ak_W7vJeKZZZ5r29sJj4TBMDx6xhirnJ5rsFPUD6TgQoPeQ3fDuq

**Comment by HristiyanG** [comment]
Please note that this is the collective amount from all the migration phases. Now we have added informational panel, where details for the 4th phase itself is displayed.
